# Generated by Django 6.0.2 on 2026-02-16 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the health benifit', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Health Benifit',
                'verbose_name_plural': 'Health Benifits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('plant_type', models.CharField(choices=[('herb', 'Herb'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('climber', 'Climber'), ('aquatic', 'Aquatic'), ('succulent', 'succulent ')], max_length=20)),
                ('region', models.CharField(choices=[('tropical', 'Tropical'), ('subtropical', 'Subtropical'), ('temperate', 'Temperate'), ('alpine', 'Alpine/Himalayan'), ('arid', 'Arid/Desert')], db_index=True, max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Plant image (botanical photograph preferred)', null=True, upload_to='plants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_benifits', models.ManyToManyField(blank=True, help_text='Select all health benefits this plant provides', related_name='plants', to='api.healthbenefit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.plant')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['plant_type', 'region'], name='api_plant_plant_t_0469ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='api_bookmar_user_id_8b647b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'plant')},
        ),
    ]
